# Generated by Django 5.2 on 2025-07-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cart_cartitem_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
