# Generated by Django 5.2 on 2025-08-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reservation_alter_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=100)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Catering Request',
                'verbose_name_plural': 'Catering Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
